"""Phase 6 evaluation contract foundation."""

from .contracts import (
    COMPONENT_ROLES,
    COVERAGE_CONTRACT_SCHEMA_VERSION,
    GTO_FPR_METRIC_ID,
    PREREGISTRATION_SCHEMA_VERSION,
    ROOT_MANIFEST_SCHEMA_VERSION,
    SELECTION_CONTRACT_SCHEMA_VERSION,
    SELECTION_REPORT_REFERENCE_SCHEMA_VERSION,
    SEMANTIC_FIXTURE_SCHEMA_VERSION,
    SEMANTIC_SOURCE_SCHEMA_VERSION,
    SERIES_REFERENCE_SCHEMA_VERSION,
    VALIDATION_BATCH_REFERENCE_SCHEMA_VERSION,
    CoverageEvaluation,
    ValidatedPhase6ContractBundle,
    artifact_ref,
    build_r008_component_source_payloads,
    build_r008_coverage_contract,
    build_r008_fixture_payloads,
    canonical_json_bytes,
    evaluate_coverage_semantics,
    load_phase6_contract_bundle,
    selection_metric_contract_payload,
    sha256_bytes,
    validate_selection_metric_contract,
)

__all__ = [
    "COMPONENT_ROLES",
    "COVERAGE_CONTRACT_SCHEMA_VERSION",
    "GTO_FPR_METRIC_ID",
    "PREREGISTRATION_SCHEMA_VERSION",
    "ROOT_MANIFEST_SCHEMA_VERSION",
    "SELECTION_CONTRACT_SCHEMA_VERSION",
    "SELECTION_REPORT_REFERENCE_SCHEMA_VERSION",
    "SEMANTIC_FIXTURE_SCHEMA_VERSION",
    "SEMANTIC_SOURCE_SCHEMA_VERSION",
    "SERIES_REFERENCE_SCHEMA_VERSION",
    "VALIDATION_BATCH_REFERENCE_SCHEMA_VERSION",
    "CoverageEvaluation",
    "ValidatedPhase6ContractBundle",
    "artifact_ref",
    "build_r008_component_source_payloads",
    "build_r008_coverage_contract",
    "build_r008_fixture_payloads",
    "canonical_json_bytes",
    "evaluate_coverage_semantics",
    "load_phase6_contract_bundle",
    "selection_metric_contract_payload",
    "sha256_bytes",
    "validate_selection_metric_contract",
]
